name: Correr Cssos de Pruebas en caso de un Pull Request

on:
  push:
    branches:
      - main  # Rama Principal
  pull_request:
    branches:
      - main  # Rama Principal

jobs:
  build:
    runs-on: ubuntu-22.04   # Cambiar si usa otra Versión o si está Obsoleta

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'  # Cambiar si usa otra Versión
          distribution: 'temurin'
          cache: 'sbt'
      - name: Ejecutar Pruebas desde el Archivo
        run: sbt test
        working-directory: ./Code